import React from "react";
import "./Dashboard.scss";
import {
    Avatar,
    Badge,
    IconButton,
    List,
    ListItem,
    ListItemAvatar,
    ListItemText,
    ListSubheader,
    Menu,
} from "@mui/material";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import MailIcon from "@mui/icons-material/Mail";
import NotificationsIcon from "@mui/icons-material/Notifications";
import Section1 from "./sections/section1/Section1";
import Section2 from "./sections/section2/Section2";
import Section3 from "./sections/section3/Section3";
import Section4 from "./sections/section4/StudentPending";
import WidgetPage from "./sections/widgets/WidgetPage";
import { useTheme } from "@mui/material/styles";

const Dashboard = () => {
    const messages = [
        {
            id: 1,
            primary: "Brunch this week?",
            secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
            person: "MathMatters",
        },
        {
            id: 2,
            primary: "Birthday Gift",
            secondary: `Do you have a suggestion for a good present for John on his work
            anniversary. I am really confused & would love your thoughts on it.`,
            person: "MathMatters",
        },
        {
            id: 3,
            primary: "Recipe to try",
            secondary: "I am try out this new BBQ recipe, I think this might be amazing",
            person: "MathMatters",
        },
        {
            id: 4,
            primary: "Yes!",
            secondary: "I have the tickets to the ReactConf for this year.",
            person: "MathMatters",
        },
        {
            id: 5,
            primary: "Doctor's Appointment",
            secondary: "My appointment for the doctor was rescheduled for next Saturday.",
            person: "MathMatters",
        },
        {
            id: 6,
            primary: "Discussion",
            secondary: `Menus that are generated by the bottom app bar (such as a bottom
            navigation drawer or overflow menu) open as bottom sheets at a higher elevation
            than the bar.`,
            person: "MathMatters",
        },
        {
            id: 7,
            primary: "Summer BBQ",
            secondary: `Who wants to have a cookout this weekend? I just got some furniture
            for my backyard and would love to fire up the grill.`,
            person: "MathMatters",
        },
    ];

    const theme = useTheme();

    const [anchorElUser, setAnchorElUser] = React.useState(null);

    const handleOpenUserMenu = (event) => {
        setAnchorElUser(event.currentTarget);
    };

    const handleCloseUserMenu = () => {
        setAnchorElUser(null);
    };

    return (
        <Box className="teacher-dashboard-content">
            <AppBar position="relative" color="primary">
                <Toolbar>
                    <Typography variant="h6">Dashboard</Typography>
                    <Box sx={{ flexGrow: 1 }} />
                    <Box sx={{ display: { xs: "none", md: "flex" } }}>
                        <IconButton size="large" aria-label="show 4 new mails" color="inherit">
                            <Badge badgeContent={4} color="error">
                                <MailIcon />
                            </Badge>
                        </IconButton>
                        <IconButton
                            size="large"
                            aria-label="show 17 new notifications"
                            color="inherit"
                            onClick={handleOpenUserMenu}
                        >
                            <Badge badgeContent={17} color="error">
                                <NotificationsIcon />
                            </Badge>
                        </IconButton>
                        <Menu
                            sx={{ mt: "45px", p: 2 }}
                            id="menu-appbar"
                            anchorEl={anchorElUser}
                            anchorOrigin={{
                                vertical: "top",
                                horizontal: "right",
                            }}
                            keepMounted
                            transformOrigin={{
                                vertical: "top",
                                horizontal: "right",
                            }}
                            open={Boolean(anchorElUser)}
                            onClose={handleCloseUserMenu}
                        >
                            <Typography variant="h6" gutterBottom component="div" sx={{ p: 2, pb: 0 }}>
                                Notifications
                            </Typography>
                            <List sx={{ mb: 2 }}>
                                {messages.map(({ id, primary, secondary, person }) => (
                                    <React.Fragment key={id}>
                                        {id === 1 && (
                                            <ListSubheader sx={{ bgcolor: "background.paper" }}>Today</ListSubheader>
                                        )}
                                        {id === 3 && (
                                            <ListSubheader sx={{ bgcolor: "background.paper" }}>
                                                Yesterday
                                            </ListSubheader>
                                        )}
                                        <ListItem button>
                                            <ListItemAvatar>
                                                <Avatar
                                                    alt="Profile Picture"
                                                    style={{
                                                        backgroundColor: theme.palette.primary.main,
                                                        color: theme.palette.primary.contrastText,
                                                    }}
                                                >
                                                    {person[0]}
                                                </Avatar>
                                            </ListItemAvatar>
                                            <ListItemText sx={{ width: 200 }}>
                                                <Typography
                                                    variant="subtitle2"
                                                    noWrap
                                                    sx={{
                                                        display: { fontWeight: 700 },
                                                        margin: "auto",
                                                    }}
                                                >
                                                    {primary}
                                                </Typography>
                                                <Typography
                                                    variant="subtitle2"
                                                    noWrap
                                                    sx={{
                                                        margin: "auto",
                                                    }}
                                                >
                                                    {secondary}
                                                </Typography>
                                            </ListItemText>
                                        </ListItem>
                                    </React.Fragment>
                                ))}
                            </List>
                        </Menu>
                    </Box>
                </Toolbar>
            </AppBar>
            <div className="content-body">
                <Section1 />
                <div className="content-items">
                    <div className="item-sections">
                        <Section2 />
                        <Section3 />
                        <Section4 />
                    </div>
                    <div className="item-widgets">
                        <WidgetPage />
                    </div>
                </div>
            </div>
        </Box>
    );
};

export default Dashboard;
